### ISSUE TITLE
Passing an empty `input` to an Operation causes a 400 `SerializationException`

### ISSUE THREAD

**Issue by sanmiguel** [wrren/baiji.ex#1]
Some requests require no arguments in the body, and because of the function clause for `Request.new/1` at https://github.com/wrren/baiji.ex/blob/master/lib/baiji/request.ex#L40-L48 the body ends up being an encoded empty string: `"\"\""`

This causes a `400` `SerializationException` when calling out to AWS.

Simply removing this special clause for an empty `input` map seems to work for us.

**Comment by wrren** [comment]
I'm seeing different behaviour on my end; the request fails if that clause is removed. Can you give an example of an API call that reproduces this behaviour?

**Comment by sanmiguel** [comment]
The error we were seeing happens during an `STS.assume_role` request. It appears the STS endpoint is not kind enough to accept the `""` body where perhaps other endpoints are?

**Comment by wrren** [comment]
I'll check this out tomorrow and see if any other endpoints exhibit this behaviour; the ones I've tested are generally fine with an empty string body and that's what HTTPoison defaults to as well.

**Comment by sanmiguel** [comment]
My apologies, I was totally mistaken when I said this affects `STS.assume_role`

I actually saw this with `Kinesis.list_streams` - I would never have passed an empty input to `STS.assume_role`...

``` elixir
iex(1)> :application.get_key(:baiji, :vsn)
{:ok, '0.6.9'}
iex(2)> Baiji.Kinesis.list_streams(%{}, [region: "us-west-2"]) |> Baiji.perform
{:error,
 "Request returned status code 400: {\"__type\":\"SerializationException\"}"}
iex(3)> Baiji.Kinesis.list_streams(%{"foo" => "bar"}, [region: "us-west-2"]) |> Baiji.perform
{:ok,
 %{"HasMoreStreams" => false,
   "StreamNames" => []}}
```

**Comment by wrren** [comment]
v0.6.10 has been published to Hex, the Kinesis list_streams function no longer returns a serialization exception.
