### ISSUE TITLE
How to set attributes for SQS GetQueueAttributes

### ISSUE THREAD

**Issue by sanmiguel** [wrren/baiji.ex#3]
When making a request to SQS `GetQueueAttributes`, it's not clear how to pass the Attribute names we want to be returned. Do you have any examples of how to do this?

We have tried inputs such as the following:

``` elixir
%{ "QueueUrl" => qurl, "AttributeNames" => ["All"] }

%{ "QueueUrl" => qurl, "Attribute.1" => "All" }

%{ "QueueUrl" => qurl, "AttributeName" => [ "All" ] }
```

but none of these seem to work. Any clues?

**Comment by wrren** [comment]
There was a query parameter encoding error in v0.6.8; most endpoints expect that list-type parameters in the query string be encoded with the key in the form 'AttributeName.member.1', but in the case of SQS some lists have an attribute in their shape called 'flattened'. When that list type is being encoded, the 'member' portion of the key apparently needed to be ommitted. I've pushed a new version that changes behaviour based on the flattened parameter and it appears to work in testing.

**Comment by wrren** [comment]
To be clear, the first of your examples was correct; it just wasn't encoding correctly!
